language: java
install: true

jdk:
  - oraclejdk8  

jobs:
  include:
    - stage: clean
      script: ./gradlew clean
    - stage: compile
      script: ./gradlew assemble
    - stage: test
      script: ./gradlew test
    - stage: linter
      script: ./gradlew check
